// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHot-TZMqYVPNUuNVcB1la3TRjRbgBZkU',
    appId: '1:157031011963:web:0efab2c0458dbc0000f4de',
    messagingSenderId: '157031011963',
    projectId: 'isdasafe-3b905',
    authDomain: 'isdasafe-3b905.firebaseapp.com',
    storageBucket: 'isdasafe-3b905.firebasestorage.app',
    measurementId: 'G-J7ZHCKYM7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARVzlbdLL23WLHpv9wp6wnDVw3_3UQYHY',
    appId: '1:157031011963:android:7d1c1d5cd4b33e8600f4de',
    messagingSenderId: '157031011963',
    projectId: 'isdasafe-3b905',
    storageBucket: 'isdasafe-3b905.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4X-k4UYRobdC-_4BC1pXsDGk5W6iwhZ4',
    appId: '1:157031011963:ios:ab2e1d1a6351eb7e00f4de',
    messagingSenderId: '157031011963',
    projectId: 'isdasafe-3b905',
    storageBucket: 'isdasafe-3b905.firebasestorage.app',
    iosBundleId: 'com.isdasafe.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4X-k4UYRobdC-_4BC1pXsDGk5W6iwhZ4',
    appId: '1:157031011963:ios:e1d1cfa3633b6c7f00f4de',
    messagingSenderId: '157031011963',
    projectId: 'isdasafe-3b905',
    storageBucket: 'isdasafe-3b905.firebasestorage.app',
    iosBundleId: 'com.example.isdasafev2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHot-TZMqYVPNUuNVcB1la3TRjRbgBZkU',
    appId: '1:157031011963:web:b1f098b2c83a434200f4de',
    messagingSenderId: '157031011963',
    projectId: 'isdasafe-3b905',
    authDomain: 'isdasafe-3b905.firebaseapp.com',
    storageBucket: 'isdasafe-3b905.firebasestorage.app',
    measurementId: 'G-2VCZH72CKV',
  );
}
